# Generated by Django 2.1 on 2019-01-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.TextField(default=5000),
        ),
    ]
