# Generated by Django 2.1 on 2019-01-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190123_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.TextField(default=''),
        ),
    ]
