# Generated by Django 2.1 on 2018-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='notice_description',
            field=models.CharField(default=' ', max_length=600),
        ),
    ]
