# Generated by Django 2.1 on 2018-12-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20181208_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notices',
            options={'ordering': ['-notice_date']},
        ),
    ]
