# Generated by Django 2.1 on 2018-12-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_auto_20181208_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notices',
            options={},
        ),
    ]
