# Generated by Django 2.1 on 2018-12-08 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_auto_20181208_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notices',
            options={'ordering': ['-notice_date_time']},
        ),
        migrations.RemoveField(
            model_name='notices',
            name='notice_date',
        ),
        migrations.AddField(
            model_name='notices',
            name='notice_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notices',
            name='notice_title',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
