# Generated by Django 2.1 on 2018-12-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20181208_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.FileField(upload_to='logo/')),
                ('footer_logo', models.FileField(upload_to='logo/')),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.IntegerField(unique=True)),
                ('fax_number', models.IntegerField(blank=True)),
            ],
        ),
    ]
