# Generated by Django 2.1 on 2019-01-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_contact_fax_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_reviewer', models.CharField(max_length=100)),
                ('testimonial_comment', models.TextField()),
            ],
        ),
    ]
