# Generated by Django 2.1 on 2019-02-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20190126_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
    ]
