# Generated by Django 2.2.1 on 2019-09-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.FileField(upload_to='about/')),
                ('about_title', models.CharField(max_length=200)),
                ('about_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField(default='')),
                ('event_image', models.FileField(upload_to='events')),
                ('event_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(default='', max_length=200)),
                ('notice_description', models.TextField(default='', max_length=600)),
                ('notice_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-notice_date_time'],
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
    ]
